// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var ML = ML || {};

/**
 * @enum {number}
 */
ML.DType = {
  FLOAT32: 0,
  FLOAT64: 1,
  INT32: 2,
  INT64: 3,
  BOOL: 4,
  STRING: 5
};

/**
 * @enum {string}
 */
ML.DTypeName = {
  '0': 'FLOAT32',
  '1': 'FLOAT64',
  '2': 'INT32',
  '3': 'INT64',
  '4': 'BOOL',
  '5': 'STRING'
};

/**
 * @enum {number}
 */
ML.ParamValue = {
  NONE: 0,
  IntVal: 1,
  FloatVal: 2,
  DoubleVal: 3,
  BoolVal: 4,
  StringVal: 5
};

/**
 * @enum {string}
 */
ML.ParamValueName = {
  '0': 'NONE',
  '1': 'IntVal',
  '2': 'FloatVal',
  '3': 'DoubleVal',
  '4': 'BoolVal',
  '5': 'StringVal'
};

/**
 * @enum {number}
 */
ML.Action = {
  FIT: 0,
  PREDICT: 1,
  SCORE: 2,
  CHECK_STATUS: 3
};

/**
 * @enum {string}
 */
ML.ActionName = {
  '0': 'FIT',
  '1': 'PREDICT',
  '2': 'SCORE',
  '3': 'CHECK_STATUS'
};

/**
 * @constructor
 */
ML.Tensor = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {ML.Tensor}
 */
ML.Tensor.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ML.Tensor=} obj
 * @returns {ML.Tensor}
 */
ML.Tensor.getRootAsTensor = function(bb, obj) {
  return (obj || new ML.Tensor).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ML.Tensor=} obj
 * @returns {ML.Tensor}
 */
ML.Tensor.getSizePrefixedRootAsTensor = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ML.Tensor).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
ML.Tensor.prototype.name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {ML.DType}
 */
ML.Tensor.prototype.dtype = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? /** @type {ML.DType} */ (this.bb.readInt8(this.bb_pos + offset)) : ML.DType.FLOAT32;
};

/**
 * @param {number} index
 * @returns {number}
 */
ML.Tensor.prototype.shape = function(index) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readInt32(this.bb.__vector(this.bb_pos + offset) + index * 4) : 0;
};

/**
 * @returns {number}
 */
ML.Tensor.prototype.shapeLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {Int32Array}
 */
ML.Tensor.prototype.shapeArray = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? new Int32Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param {number} index
 * @returns {number}
 */
ML.Tensor.prototype.data = function(index) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readUint8(this.bb.__vector(this.bb_pos + offset) + index) : 0;
};

/**
 * @returns {number}
 */
ML.Tensor.prototype.dataLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {Uint8Array}
 */
ML.Tensor.prototype.dataArray = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? new Uint8Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
ML.Tensor.startTensor = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} nameOffset
 */
ML.Tensor.addName = function(builder, nameOffset) {
  builder.addFieldOffset(0, nameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {ML.DType} dtype
 */
ML.Tensor.addDtype = function(builder, dtype) {
  builder.addFieldInt8(1, dtype, ML.DType.FLOAT32);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} shapeOffset
 */
ML.Tensor.addShape = function(builder, shapeOffset) {
  builder.addFieldOffset(2, shapeOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<number>} data
 * @returns {flatbuffers.Offset}
 */
ML.Tensor.createShapeVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt32(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
ML.Tensor.startShapeVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} dataOffset
 */
ML.Tensor.addData = function(builder, dataOffset) {
  builder.addFieldOffset(3, dataOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<number>} data
 * @returns {flatbuffers.Offset}
 */
ML.Tensor.createDataVector = function(builder, data) {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
ML.Tensor.startDataVector = function(builder, numElems) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
ML.Tensor.endTensor = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} nameOffset
 * @param {ML.DType} dtype
 * @param {flatbuffers.Offset} shapeOffset
 * @param {flatbuffers.Offset} dataOffset
 * @returns {flatbuffers.Offset}
 */
ML.Tensor.createTensor = function(builder, nameOffset, dtype, shapeOffset, dataOffset) {
  ML.Tensor.startTensor(builder);
  ML.Tensor.addName(builder, nameOffset);
  ML.Tensor.addDtype(builder, dtype);
  ML.Tensor.addShape(builder, shapeOffset);
  ML.Tensor.addData(builder, dataOffset);
  return ML.Tensor.endTensor(builder);
}

/**
 * @constructor
 */
ML.IntVal = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {ML.IntVal}
 */
ML.IntVal.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ML.IntVal=} obj
 * @returns {ML.IntVal}
 */
ML.IntVal.getRootAsIntVal = function(bb, obj) {
  return (obj || new ML.IntVal).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ML.IntVal=} obj
 * @returns {ML.IntVal}
 */
ML.IntVal.getSizePrefixedRootAsIntVal = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ML.IntVal).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
ML.IntVal.prototype.value = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
ML.IntVal.startIntVal = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} value
 */
ML.IntVal.addValue = function(builder, value) {
  builder.addFieldInt32(0, value, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
ML.IntVal.endIntVal = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} value
 * @returns {flatbuffers.Offset}
 */
ML.IntVal.createIntVal = function(builder, value) {
  ML.IntVal.startIntVal(builder);
  ML.IntVal.addValue(builder, value);
  return ML.IntVal.endIntVal(builder);
}

/**
 * @constructor
 */
ML.FloatVal = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {ML.FloatVal}
 */
ML.FloatVal.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ML.FloatVal=} obj
 * @returns {ML.FloatVal}
 */
ML.FloatVal.getRootAsFloatVal = function(bb, obj) {
  return (obj || new ML.FloatVal).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ML.FloatVal=} obj
 * @returns {ML.FloatVal}
 */
ML.FloatVal.getSizePrefixedRootAsFloatVal = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ML.FloatVal).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
ML.FloatVal.prototype.value = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
ML.FloatVal.startFloatVal = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} value
 */
ML.FloatVal.addValue = function(builder, value) {
  builder.addFieldFloat32(0, value, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
ML.FloatVal.endFloatVal = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} value
 * @returns {flatbuffers.Offset}
 */
ML.FloatVal.createFloatVal = function(builder, value) {
  ML.FloatVal.startFloatVal(builder);
  ML.FloatVal.addValue(builder, value);
  return ML.FloatVal.endFloatVal(builder);
}

/**
 * @constructor
 */
ML.DoubleVal = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {ML.DoubleVal}
 */
ML.DoubleVal.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ML.DoubleVal=} obj
 * @returns {ML.DoubleVal}
 */
ML.DoubleVal.getRootAsDoubleVal = function(bb, obj) {
  return (obj || new ML.DoubleVal).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ML.DoubleVal=} obj
 * @returns {ML.DoubleVal}
 */
ML.DoubleVal.getSizePrefixedRootAsDoubleVal = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ML.DoubleVal).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
ML.DoubleVal.prototype.value = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
ML.DoubleVal.startDoubleVal = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} value
 */
ML.DoubleVal.addValue = function(builder, value) {
  builder.addFieldFloat64(0, value, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
ML.DoubleVal.endDoubleVal = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} value
 * @returns {flatbuffers.Offset}
 */
ML.DoubleVal.createDoubleVal = function(builder, value) {
  ML.DoubleVal.startDoubleVal(builder);
  ML.DoubleVal.addValue(builder, value);
  return ML.DoubleVal.endDoubleVal(builder);
}

/**
 * @constructor
 */
ML.BoolVal = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {ML.BoolVal}
 */
ML.BoolVal.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ML.BoolVal=} obj
 * @returns {ML.BoolVal}
 */
ML.BoolVal.getRootAsBoolVal = function(bb, obj) {
  return (obj || new ML.BoolVal).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ML.BoolVal=} obj
 * @returns {ML.BoolVal}
 */
ML.BoolVal.getSizePrefixedRootAsBoolVal = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ML.BoolVal).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {boolean}
 */
ML.BoolVal.prototype.value = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param {flatbuffers.Builder} builder
 */
ML.BoolVal.startBoolVal = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} value
 */
ML.BoolVal.addValue = function(builder, value) {
  builder.addFieldInt8(0, +value, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
ML.BoolVal.endBoolVal = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} value
 * @returns {flatbuffers.Offset}
 */
ML.BoolVal.createBoolVal = function(builder, value) {
  ML.BoolVal.startBoolVal(builder);
  ML.BoolVal.addValue(builder, value);
  return ML.BoolVal.endBoolVal(builder);
}

/**
 * @constructor
 */
ML.StringVal = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {ML.StringVal}
 */
ML.StringVal.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ML.StringVal=} obj
 * @returns {ML.StringVal}
 */
ML.StringVal.getRootAsStringVal = function(bb, obj) {
  return (obj || new ML.StringVal).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ML.StringVal=} obj
 * @returns {ML.StringVal}
 */
ML.StringVal.getSizePrefixedRootAsStringVal = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ML.StringVal).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
ML.StringVal.prototype.value = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
ML.StringVal.startStringVal = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} valueOffset
 */
ML.StringVal.addValue = function(builder, valueOffset) {
  builder.addFieldOffset(0, valueOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
ML.StringVal.endStringVal = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} valueOffset
 * @returns {flatbuffers.Offset}
 */
ML.StringVal.createStringVal = function(builder, valueOffset) {
  ML.StringVal.startStringVal(builder);
  ML.StringVal.addValue(builder, valueOffset);
  return ML.StringVal.endStringVal(builder);
}

/**
 * @constructor
 */
ML.Param = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {ML.Param}
 */
ML.Param.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ML.Param=} obj
 * @returns {ML.Param}
 */
ML.Param.getRootAsParam = function(bb, obj) {
  return (obj || new ML.Param).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ML.Param=} obj
 * @returns {ML.Param}
 */
ML.Param.getSizePrefixedRootAsParam = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ML.Param).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
ML.Param.prototype.key = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {ML.ParamValue}
 */
ML.Param.prototype.valueType = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? /** @type {ML.ParamValue} */ (this.bb.readUint8(this.bb_pos + offset)) : ML.ParamValue.NONE;
};

/**
 * @param {flatbuffers.Table} obj
 * @returns {?flatbuffers.Table}
 */
ML.Param.prototype.value = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
ML.Param.startParam = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} keyOffset
 */
ML.Param.addKey = function(builder, keyOffset) {
  builder.addFieldOffset(0, keyOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {ML.ParamValue} valueType
 */
ML.Param.addValueType = function(builder, valueType) {
  builder.addFieldInt8(1, valueType, ML.ParamValue.NONE);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} valueOffset
 */
ML.Param.addValue = function(builder, valueOffset) {
  builder.addFieldOffset(2, valueOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
ML.Param.endParam = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} keyOffset
 * @param {ML.ParamValue} valueType
 * @param {flatbuffers.Offset} valueOffset
 * @returns {flatbuffers.Offset}
 */
ML.Param.createParam = function(builder, keyOffset, valueType, valueOffset) {
  ML.Param.startParam(builder);
  ML.Param.addKey(builder, keyOffset);
  ML.Param.addValueType(builder, valueType);
  ML.Param.addValue(builder, valueOffset);
  return ML.Param.endParam(builder);
}

/**
 * @constructor
 */
ML.Request = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {ML.Request}
 */
ML.Request.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ML.Request=} obj
 * @returns {ML.Request}
 */
ML.Request.getRootAsRequest = function(bb, obj) {
  return (obj || new ML.Request).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ML.Request=} obj
 * @returns {ML.Request}
 */
ML.Request.getSizePrefixedRootAsRequest = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ML.Request).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {ML.Action}
 */
ML.Request.prototype.action = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? /** @type {ML.Action} */ (this.bb.readInt8(this.bb_pos + offset)) : ML.Action.FIT;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
ML.Request.prototype.type = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
ML.Request.prototype.id = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
ML.Request.prototype.name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {number} index
 * @param {ML.Param=} obj
 * @returns {ML.Param}
 */
ML.Request.prototype.params = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? (obj || new ML.Param).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
ML.Request.prototype.paramsLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {ML.Tensor=} obj
 * @returns {ML.Tensor|null}
 */
ML.Request.prototype.x = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? (obj || new ML.Tensor).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {ML.Tensor=} obj
 * @returns {ML.Tensor|null}
 */
ML.Request.prototype.y = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? (obj || new ML.Tensor).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
ML.Request.startRequest = function(builder) {
  builder.startObject(7);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {ML.Action} action
 */
ML.Request.addAction = function(builder, action) {
  builder.addFieldInt8(0, action, ML.Action.FIT);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} typeOffset
 */
ML.Request.addType = function(builder, typeOffset) {
  builder.addFieldOffset(1, typeOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 */
ML.Request.addId = function(builder, idOffset) {
  builder.addFieldOffset(2, idOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} nameOffset
 */
ML.Request.addName = function(builder, nameOffset) {
  builder.addFieldOffset(3, nameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} paramsOffset
 */
ML.Request.addParams = function(builder, paramsOffset) {
  builder.addFieldOffset(4, paramsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
ML.Request.createParamsVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
ML.Request.startParamsVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} xOffset
 */
ML.Request.addX = function(builder, xOffset) {
  builder.addFieldOffset(5, xOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} yOffset
 */
ML.Request.addY = function(builder, yOffset) {
  builder.addFieldOffset(6, yOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
ML.Request.endRequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
ML.Request.finishRequestBuffer = function(builder, offset) {
  builder.finish(offset);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
ML.Request.finishSizePrefixedRequestBuffer = function(builder, offset) {
  builder.finish(offset, undefined, true);
};

/**
 * @constructor
 */
ML.Response = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {ML.Response}
 */
ML.Response.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ML.Response=} obj
 * @returns {ML.Response}
 */
ML.Response.getRootAsResponse = function(bb, obj) {
  return (obj || new ML.Response).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ML.Response=} obj
 * @returns {ML.Response}
 */
ML.Response.getSizePrefixedRootAsResponse = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ML.Response).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
ML.Response.prototype.status = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
ML.Response.prototype.message = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {number} index
 * @param {ML.Tensor=} obj
 * @returns {ML.Tensor}
 */
ML.Response.prototype.tensors = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new ML.Tensor).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
ML.Response.prototype.tensorsLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
ML.Response.startResponse = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} status
 */
ML.Response.addStatus = function(builder, status) {
  builder.addFieldInt32(0, status, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} messageOffset
 */
ML.Response.addMessage = function(builder, messageOffset) {
  builder.addFieldOffset(1, messageOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} tensorsOffset
 */
ML.Response.addTensors = function(builder, tensorsOffset) {
  builder.addFieldOffset(2, tensorsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
ML.Response.createTensorsVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
ML.Response.startTensorsVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
ML.Response.endResponse = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} status
 * @param {flatbuffers.Offset} messageOffset
 * @param {flatbuffers.Offset} tensorsOffset
 * @returns {flatbuffers.Offset}
 */
ML.Response.createResponse = function(builder, status, messageOffset, tensorsOffset) {
  ML.Response.startResponse(builder);
  ML.Response.addStatus(builder, status);
  ML.Response.addMessage(builder, messageOffset);
  ML.Response.addTensors(builder, tensorsOffset);
  return ML.Response.endResponse(builder);
}

// Exports for Node.js and RequireJS
// this.ML = ML;
export default ML;

