# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ML

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BoolVal(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsBoolVal(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BoolVal()
        x.Init(buf, n + offset)
        return x

    # BoolVal
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BoolVal
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def BoolValStart(builder): builder.StartObject(1)
def BoolValAddValue(builder, value): builder.PrependBoolSlot(0, value, 0)
def BoolValEnd(builder): return builder.EndObject()
