# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ML

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FloatVal(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsFloatVal(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FloatVal()
        x.Init(buf, n + offset)
        return x

    # FloatVal
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FloatVal
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def FloatValStart(builder): builder.StartObject(1)
def FloatValAddValue(builder, value): builder.PrependFloat32Slot(0, value, 0.0)
def FloatValEnd(builder): return builder.EndObject()
