# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ML

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class IntVal(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsIntVal(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = IntVal()
        x.Init(buf, n + offset)
        return x

    # IntVal
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # IntVal
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def IntValStart(builder): builder.StartObject(1)
def IntValAddValue(builder, value): builder.PrependInt32Slot(0, value, 0)
def IntValEnd(builder): return builder.EndObject()
