# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ML

class ParamValue(object):
    NONE = 0
    IntVal = 1
    FloatVal = 2
    DoubleVal = 3
    BoolVal = 4
    StringVal = 5

