# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ML

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StringVal(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsStringVal(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StringVal()
        x.Init(buf, n + offset)
        return x

    # StringVal
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StringVal
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def StringValStart(builder): builder.StartObject(1)
def StringValAddValue(builder, value): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)
def StringValEnd(builder): return builder.EndObject()
